### ISSUE TITLE
Regular framework support (use without CocoaPods)

### ISSUE THREAD

**Issue by StefanOltmann** [getsentry/sentry-kotlin-multiplatform#118]
### Problem Statement

I don't like CocoaPods. They're complicated and not a great solution at all.

### Solution Brainstorm

Could a Gradle script be utilized to facilitate the copying or updating of the XCFramework to its designated location?

Alternatively, a more streamlined approach could involve developing a completely Kotlin-based version of the SDK, thereby replacing the existing iteration with an XCFramework generated through Kotlin/Native.

**Comment by buenaflor** [comment]
Alternatively if that is an option for you, you can also use SPM to include the sentry-cocoa dependency:

https://docs.sentry.io/platforms/kotlin-multiplatform/install/swift-package-manager/?original_referrer=https%3A%2F%2Fwww.google.com%2F

The only caveat here currently is that you need to export it as a static framework. Some context as to why and how to fix this here #108

**Comment by StefanOltmann** [comment]
I presently utilize the Sentry XCFramework, which is provided as a ZIP file on the releases page, and this setup serves me well. I have contemplated transitioning to the Multiplatform option to streamline my codebase, although I am reluctant to do so if it involves incorporating CocoaPods.

**Comment by buenaflor** [comment]
You don't necessarily need cocoapods. The only thing you need for the SDK to work is providing the sentry-cocoa SDK binary. I haven't checked on how a pre-built XCFramework needs to be linked in this case.

It might be as easy as `linkerOpts("-framework", "MyFramework", "-F/path/to/framework/")`

But I'll check that out and get back to you on how to configure it.

**Comment by StefanOltmann** [comment]
Thank you, I will try that.
I wonder why only the simulator needs that and not the other targets.

**Comment by buenaflor** [comment]
Sry, should've added the rest of the code. You will need to specify each target and the respective framework of course

**Comment by msasikanth** [comment]
Hi, I have noticed an issue when migrating from cocoapods to regular framework. So flagging it here.

After removing cocoapods plugin from KMP, I have added Sentry cocoa dependency using SPM and the ran app from Xcode and everything worked correctly. But when I tried to run the iOS tests in the common module. I keep getting this error, not entirely sure how I can resolve this. Didn't had this issue when using pod dependency.

```
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_PrivateSentrySDKOnly", referenced from:
      objc-class-ref in result.o
  "_OBJC_CLASS_$_SentryAttachment", referenced from:
      objc-class-ref in result.o
  "_OBJC_CLASS_$_SentryBreadcrumb", referenced from:
      objc-class-ref in result.o
  "_OBJC_CLASS_$_SentryDependencyContainer", referenced from:
      objc-class-ref in result.o
  "_OBJC_CLASS_$_SentryEnvelope", referenced from:
      objc-class-ref in result.o
  "_OBJC_CLASS_$_SentryEnvelopeHeader", referenced from:
      objc-class-ref in result.o
  "_OBJC_CLASS_$_SentryEnvelopeItem", referenced from:
      objc-class-ref in result.o
  "_OBJC_CLASS_$_SentryEvent", referenced from:
      objc-class-ref in result.o
  "_OBJC_CLASS_$_SentryException", referenced from:
      objc-class-ref in result.o
  "_OBJC_CLASS_$_SentryHttpStatusCodeRange", referenced from:
      objc-class-ref in result.o
  "_OBJC_CLASS_$_SentryId", referenced from:
      objc-class-ref in result.o
  "_OBJC_CLASS_$_SentryMechanism", referenced from:
      objc-class-ref in result.o
  "_OBJC_CLASS_$_SentryMessage", referenced from:
      objc-class-ref in result.o
  "_OBJC_CLASS_$_SentrySDK", referenced from:
      objc-class-ref in result.o
  "_OBJC_CLASS_$_SentryScope", referenced from:
      objc-class-ref in result.o
  "_OBJC_CLASS_$_SentryUser", referenced from:
      objc-class-ref in result.o
  "_OBJC_CLASS_$_SentryUserFeedback", referenced from:
      objc-class-ref in result.o
ld: symbol(s) not found for architecture arm64
```

**Comment by buenaflor** [comment]
@msasikanth

hi, please refer to our [sentry doc](https://docs.sentry.io/platforms/kotlin-multiplatform/install/swift-package-manager/?original_referrer=https%3A%2F%2Fwww.google.com%2F) on how to set it up. 

Essentially you need to export your shared framework as static (for now)

As for your error, read #108 if you like to understand why this is happening.

**Comment by msasikanth** [comment]
> 

Got it. The framework is already static, I think I would have to mark those symbols as undefined like you mentioned in the issue. Thanks 👍🏾
