### ISSUE TITLE
iOS stacktraces are not symbolicate 

### ISSUE THREAD

**Issue by ynsok** [getsentry/sentry-kotlin-multiplatform#122]
### Platform

Apple

### Installed

Swift Package Manager

### Version

0.2.1

### Steps to Reproduce
<img width="1002" alt="Zrzut ekranu 2023-10-20 o 13 51 49" src="https://github.com/getsentry/sentry-kotlin-multiplatform/assets/30358511/a85cb3d0-4ea6-4736-90f1-653fd8182afd">

<img width="1265" alt="Zrzut ekranu 2023-10-20 o 10 24 53" src="https://github.com/getsentry/sentry-kotlin-multiplatform/assets/30358511/5f91a57f-6734-4389-a21d-c35677420fff">

### Expected Result

I would like to see readable stacktrace

### Actual Result

<img width="1141" alt="Zrzut ekranu 2023-10-20 o 11 50 46" src="https://github.com/getsentry/sentry-kotlin-multiplatform/assets/30358511/0977a34f-bd8f-43cb-833b-c811816bb530">

<img width="1275" alt="Zrzut ekranu 2023-10-20 o 11 58 44" src="https://github.com/getsentry/sentry-kotlin-multiplatform/assets/30358511/20a20b07-0f7c-438a-8b27-62e4cb4ed307">

<img width="1342" alt="Zrzut ekranu 2023-10-20 o 11 59 11" src="https://github.com/getsentry/sentry-kotlin-multiplatform/assets/30358511/7788b686-9753-43bb-99d5-34b525664a8f">

**Comment by buenaflor** [comment]
Hi!

maybe unrelated but I'm wondering why you can compile it with SPM without setting `isStatic = true`in the binary framework configuration. 

Which Kotlin version are you using?

Also check out our KMP sample with SPM if you like.

**Comment by ynsok** [comment]
You are right, I for mistake in deleting this before taking a screenshot. I've edited the post.

`kotlin_version = 1.8.22`

Yes, I've checked but without success

**Comment by buenaflor** [comment]
I see you're running self hosted, is the outcome the same on sentry.io?

**Comment by ynsok** [comment]
Could you explain how can i check if the outcome is the same on sentry.io?

**Comment by buenaflor** [comment]
Check if your stacktrace is symbolicated on sentry.io not self hosted. 

I currently cannot find any issues with your setup so that might be good to check.

**Comment by ynsok** [comment]
Okay, so I've created my own project and migrated the iOS configuration to connect with my sentry and I've ended up with this.

<img width="1096" alt="Zrzut ekranu 2023-10-20 o 16 53 01" src="https://github.com/getsentry/sentry-kotlin-multiplatform/assets/30358511/5440914a-41dc-4e31-bc3d-f7d124644f8f">

**Comment by buenaflor** [comment]
This looks as expected with the SDKs current state, so I assume there's an issue with self hosted. 

Might be worth checking if the same happens with Sentry Cocoa used directly in native iOS without KMP but I doubt it's different.

**Comment by ynsok** [comment]
I've checked and is Not working.

Do you have any clue what can be wrong in self hosted?

**Comment by romtsn** [comment]
@ynsok what's the version of self-hosted you're using?

**Comment by ynsok** [comment]
Sentry 23.3.1

**Comment by Swatinem** [comment]
The fact that you have no "Debug File Candidates" might hint at a problem that Symbolicator is unable to query those from Sentry.
On the other hand though, the list should report those files as `unused` in that case.

Can you check the detailed logs of your self-hosted Symbolicator?
