### ISSUE TITLE
The Ability to Adjust App Hang Preferences 

### ISSUE THREAD

**Issue by alexwhb** [getsentry/sentry-kotlin-multiplatform#179]
### Problem Statement

I've seen in the individual iOS & Android libraries you can configure the hang detection for a number of milliseconds or disable it all together. It'd be really great to have this in the multiplatform library. Or if there's a way to do it currently I'd love to be pointed in the right direction on how to do that.

**Comment by buenaflor** [comment]
hey! yea totally, we can add that option.

To be sure, you are looking for 

Cocoa:
- `enableAppHangTracking` and `appHangTimeoutInterval`

Android:
- `anrEnabled` and `anrTimeoutIntervalMillis`

**Comment by alexwhb** [comment]
Yes exactly! That would be awesome!

**Comment by buenaflor** [comment]
Still need to discuss this internally whether to separate the options or combine them

**Comment by buenaflor** [comment]
We decided to keep them separate similar to the Flutter and RN SDKs to avoid confusion
