### ISSUE TITLE
Make `setSentryUnhandledExceptionHook` public

### ISSUE THREAD

**Issue by chrisbanes** [getsentry/sentry-kotlin-multiplatform#200]
### Problem Statement

We have a mixed KMP and native app, meaning that the limited configuration options available via this library, limit what we can enable on both the Android and iOS sides.

On the iOS side, AFAICT the only thing library does is called `SentrySDK` along with setting an unhandled exception handler. 

### Solution Brainstorm

Since I would rather call `SentrySDK.start {}` in Swift, can we make the [setSentryUnhandledExceptionHook](https://github.com/getsentry/sentry-kotlin-multiplatform/blob/main/sentry-kotlin-multiplatform/src/appleMain/kotlin/io/sentry/kotlin/multiplatform/nsexception/SentryUnhandledExceptions.kt#L52C14-L52C45) function public?

**Comment by romtsn** [comment]
hi @chrisbanes thanks for the FR, I think this makes sense to expose it, we'll discuss internally and make it public in the next SDK version. Will keep you posted!

**Comment by buenaflor** [comment]
This is now released with `0.6.0`
