### ISSUE TITLE
Expose platform specific Configuration via expect actual

### ISSUE THREAD

**Issue by Legion2** [getsentry/sentry-kotlin-multiplatform#213]
### Problem Statement

I want to configure underlying configurations in android and ios SDK, which are not jetzt available in the common configuration.

### Solution Brainstorm

Create an expected type for the configuration in common code and add actual implementations of it in the platforms. The users can then also use expect/actual to configure the actual platform configuration as needed, without there being a common mapping between them.

**Comment by Legion2** [comment]
We would like to try out the React Native session replay alpha (https://github.com/getsentry/sentry-react-native/issues/2703), but can not apply the required configuration in sentry android and ios SDK.

**Comment by buenaflor** [comment]
> Create an expected type for the configuration in common code and add actual implementations of it in the platforms. The users can then also use expect/actual to configure the actual platform configuration as needed, without there being a common mapping between them.

can you give a simple example?

**Comment by Legion2** [comment]
```kotlin
// common
expect class PlatformConfigurationOptions

// android
actual typealias PlatformConfigurationOptions = SentryAndroidOptions // class from android sdk

// ios
actual typealias PlatformConfigurationOptions = SentryiOSOptions // class from ios sdk
```

**Comment by buenaflor** [comment]
Okay understand

This should work, theoretically, but testing it, there's some issue with typealiasing the JVM sentryoptions and Android sentry options where you cannot access the properties. have you been able to successfully implement this locally?

**Comment by buenaflor** [comment]
Odd thing is that it works directly in the SDK but when consumed by another application (e.g our sample app) it fails

**Comment by buenaflor** [comment]
Okay got it why it didn't work, it requires us to expose the internal native API's with `api('java_sdk_dependency)`. 

It is possible and simplifies the customization of the native SDK tbh. We generally haven't used `actual typealias` yet because it requires exposing the internal Sentry Native SDK dependencies.

Tbh might be worth it but I'll talk to my team and see if we have any concerns about that

**Comment by Legion2** [comment]
If you don't want to expose the dependency on the android SDK, you can specify it in the documentation, that users that want to use the platform config should add the dependency on the android SDK themselves to their projects.

**Comment by buenaflor** [comment]
I'm generally thinking about exposing them since it would reduce the internal jvm/android implementation side immensely if we can internally use typealias as much as possible as well

But good point, regardless we can document that in the docs

**Comment by buenaflor** [comment]
@romtsn thoughts on exposing Sentry/Sentry-android API with `api("java/android_sdk_dependency")` so we can use `actual typealias`? 

One of the major cons would be that user could have access to `io.sentry.Sentry` and `io.sentry.kotlin.multiplatform.Sentry` in the jvm/android sourceSets.

**Comment by Legion2** [comment]
This would also mean user can bypass some code in the multiplatform wrapper, I don't know if there is anything important. But this can also happen already if users manually included the android sdk or are migrating from android sdk to multiplatform sdk.

**Comment by romtsn** [comment]
yeah tbh, I think the way forward is to tell the users to manually add and configure the Android SDK and have a flag to disable native initialization (similarly to how we do that in [RN](https://docs.sentry.io/platforms/react-native/manual-setup/native-init/) and[ Flutter](https://docs.sentry.io/platforms/flutter/native-init/)), to align with other hybrid SDKs, what do you think?

**Comment by romtsn** [comment]
on the other hand, RN and Flutter don't have expect/actual mechanisms, so this might be a nice feature of the KMP sdk, so I'm on the fence here

**Comment by buenaflor** [comment]
Even though it might not align exactly with the other hybrid SDKs I think doing it the "KMP" way is more intuitive and easier for the user.

As an example of how it could look like from the user perspective

```
// commonMain
fun init() {
  Sentry.init(getPlatformOptions())
}

expect fun getPlatformOptions(): PlatformOptions

// iOS
actual fun getPlatformOptions(): PlatformOptions {
  return SentryCocoaOptions(...)
}

// Android
actual fun getPlatformOptions(): PlatformOptions {
  return SentryAndroidOptions(...)
}
```

**Comment by Legion2** [comment]
We are using the KMP sdk together with the RN sdk and use the disable native initialization in RN, because it would else override settings done in kotlin. However I think it lacks documentation on what features of the sdk are not working if you disable native initialization. Example we updated RN sdk to use session recordings and configured the options in RN, but because native initialization was disabled it did not work, because we now have to enable the correct settings in the KMP/Native sdk our self and there is not much documentation for which are the corresponding options. What we are doing is looking at the source code of RN sdk to find out what settings it uses in the native SDK, so we can set this then manually.

So there is a drawback on allowing to disable native initialization.

**Comment by romtsn** [comment]
@buenaflor yeah looks reasonable, let's do that then!

**Comment by buenaflor** [comment]
Cool!

Now we have two options for making this work:
- We set `api("java/android_sdk_dependency")` internally instead of `implementation` 
- The user adds `implementation("java/android_sdk_dependency")` to their android's build.gradle dependencies and we document it

The pro of the first option is that we can freely use actual typealias in the SDK ourselves which would be nice for us and the user doesn't have to do anything else
