### ISSUE TITLE
XCode build fails due to XCFramework names issue

### ISSUE THREAD

**Issue by oblakr24** [getsentry/sentry-kotlin-multiplatform#255]
### Problem Statement

My main issue is that it is unclear to me which Kotlin version is supported, specifically for iOS. 
Android and JVM work fine.

For iOS, the installation instructions do not work for me as I keep getting issues during the XCode build:

```
All inner frameworks in XCFramework 'composeApp' should have same names. But there are two with 'composeApp' and 'shared' names

```

My cocoapods block:

```
   cocoapods {
        // Required properties
        // Specify the required Pod version here. Otherwise, the Gradle project version is used.
        version = "1.0"
        summary = "Some description for a Kotlin/Native module"
        homepage = "Link to a Kotlin/Native module homepage"

        ios.deploymentTarget = "14.1"
        podfile = project.file("../iosApp/Podfile")
        // Make sure you use the proper version according to our Cocoa SDK Version Compatibility Table.
        pod("Sentry") {
            version = "~> 8.25"
            linkOnly = true
            moduleName = "Sentry"
            extraOpts += listOf("-compiler-option", "-fmodules")
        }
        framework {
            baseName = "shared"
        }
    }
```

If I try to name this framework as `composeApp`, then I get another error:

```
'embedAndSign' task can not be used in a project with dependencies to pods.

```

**Comment by buenaflor** [comment]
hey, what kotlin version are you using?

**Comment by oblakr24** [comment]
@buenaflor  hi, I tried with 2.0.0 and 2.0.10

**Comment by buenaflor** [comment]
Thx for the quick response, I'll check it out and get back to you! there may be something wrong though since we still use `1.9.23`. 

Do you know if it works on a KMP only project for you? as far as I can see you're also using compose multiplatform

**Comment by oblakr24** [comment]
Hi, unfortunately i did not try KMP only, but it might be the same issue there, just that the error would complain about a different name (`ComposeApp` is the default framework name from the wizard for Compose Multiplatform).

**Comment by buenaflor** [comment]
Is this still a problem? Could you check it out on a new sample app? from some quick testing it works fine on my end

**Comment by OskarPersson** [comment]
@oblakr24 How did you solve this? I'm still getting the embedAndSign-error with Kotlin 2.1.0.


libs.versions.toml:

```
[versions]

kotlin = "2.1.0"
sentry = "0.10.0"

[plugins]
kotlinCocoapods = { id = "org.jetbrains.kotlin.native.cocoapods", version.ref = "kotlin" }
sentry = { id = "io.sentry.kotlin.multiplatform.gradle", version.ref = "sentry" }
```

shared/build.gradle.kts:

```
plugins {
    alias(libs.plugins.kotlinCocoapods)
    alias(libs.plugins.sentry)
}

...

kotlin {
    ...

    cocoapods {
        summary = "Some description for the Shared Module"
        homepage = "Link to the Shared Module homepage"
        version = "1.0"
        ios.deploymentTarget = "17.0"
        podfile = project.file("../iosApp/Podfile")
        pod("Sentry") {
            version = "~> 8.36"
            linkOnly = true
            extraOpts += listOf("-compiler-option", "-fmodules")
        }
    }
}
```

iosApp/Podfile:

```
target 'myAppName' do
  use_frameworks!
  platform :ios, '17.0'
  pod 'shared', :path => '../shared'
end
```

The android app of the project works fine and is able to send an event to Sentry.

**Comment by OskarPersson** [comment]
Adding `kotlin.apple.deprecated.allowUsingEmbedAndSignWithCocoaPodsDependencies=true` gradle.properties "solves" the embedAndSign-error but instead creates a new one:

```
ld: framework 'Sentry' not found
```
