### ISSUE TITLE
Missing cinterop for SentrySessionReplayIntegration

### ISSUE THREAD

**Issue by Legion2** [getsentry/sentry-kotlin-multiplatform#271]
### Problem Statement

I want to use session replay on mobile, but on ios the cinterop is missing some types.

### Solution Brainstorm

I want to be able to configure session replay in kotlin multiplatform code. Or atleast have access to the objectc definitions

**Comment by buenaflor** [comment]
hey which sentry cocoa and kmp version are you using?

**Comment by Legion2** [comment]
kmp 0.9.0 and cocoa 8.36.0

**Comment by buenaflor** [comment]
can you check if the same problem exists on 0.8.0

**Comment by Legion2** [comment]
I cannot downgrade, because i use the mobile replay which is only available in 0.9.0

**Comment by buenaflor** [comment]
0.8.0 internally uses cocoa version 8.36.0 to create the cinterop bindings so theoretically it should also have the replay options

**Comment by Legion2** [comment]
But the android version in 0.8.0 is too old and doesn't support session replay

**Comment by buenaflor** [comment]
how do you use the KMP init btw? 

`Sentry.init` or `Sentry.initWithPlatformOptions`

**Comment by Legion2** [comment]
I use Sentry.initWithPlatformOptions to access the replay API which is not available in common code.

**Comment by buenaflor** [comment]
it is available for me locally:

```kotlin
actual fun createPlatformOptionsConfiguration(): PlatformOptionsConfiguration = {
    it.dsn = "..."
    it.experimental.sessionReplay() // replay config
}
```

this is tested in the sample app in the kmp repo

**Comment by buenaflor** [comment]
if you want to access it in common code I'll add it soon
