### ISSUE TITLE
Expose isEnabled from underlying Sentry SDKs

### ISSUE THREAD

**Issue by kodebach** [getsentry/sentry-kotlin-multiplatform#272]
### Problem Statement

We do not enable Sentry in all our app's build configurations. If it is disabled, we hide certain parts of the UI. For this we use `Sentry.isEnabled()`, which exists in both the JVM and Apple SDKs. However, it is not exposed in the multiplatform SDK, so we need to use a custom `expect`/`actual` function for that.

### Solution Brainstorm

In `io.sentry.kotlin.multiplatform.Sentry` add `isEnabled()` that calls `isEnabled()` from the platform SDKs.

**Comment by buenaflor** [comment]
Thanks for the request 👍 

Will add it
