### ISSUE TITLE
Library not loaded: @rpath/Sentry.framework/Sentry when running iOS app

### ISSUE THREAD

**Issue by jollygreenegiant** [getsentry/sentry-kotlin-multiplatform#274]
### Platform

Apple

### Installed

CocoaPods

### Version

8.25

### Steps to Reproduce

In my Compose Multiplatform app:

cocoapods setup in build.gradle:
```
cocoapods {
    version = "1.0"
    podfile = project.file("../iosApp/Podfile")
    name = "ComposeApp"
    homepage = "<app website>"
    summary = "<app summary>"
    ios.deploymentTarget = "17.0"
    pod("Sentry") {
        version = "8.25"
        linkOnly = true
        extraOpts += listOf("-compiler-option", "-fmodules")
    }
    framework {
        baseName = "composeApp"
    }
}
```

Podfile:
```
source 'https://cdn.cocoapods.org'

platform :ios, '18.0'

target 'iosApp' do
    pod 'Sentry', '8.25'
    pod 'ComposeApp', :path => '../composeApp'
end
```

### Expected Result

Sentry should be available in the iOS app

### Actual Result

Gradle syncs correctly and the iosApp builds in XCode, but when I run the iosApp target I get the following error:

```
dyld[32909]: Library not loaded: @rpath/Sentry.framework/Sentry

Reason: tried: '/Users/<user>/Library/Developer/Xcode/DerivedData/iosApp-aslbvzmwwjgwgegxsbzuczosebxp/Build/Products/Debug-iphonesimulator/Sentry.framework/Sentry' (no such file)
```

It looks like CocoaPods isn't generating a Frameworks file for Sentry and I'm not sure why or how to fix it.  I am a Kotlin dev and am brand new to Compose Multiplatform and pretty new to iOS in general, so any help would be much appreciated.

**Comment by buenaflor** [comment]
Hey did you add this to the podfile manually? `pod 'Sentry', '8.25'`

The cocoapods will handle configuring the dependency and will update the podfile.lock file so this is not needed

**Comment by jollygreenegiant** [comment]
@buenaflor I did add that manually - I just removed it, closed XCode, did a gradle sync, `pod deintegrate` and `pod update` and getting the same error when running the iosApp.  Podfile now looks like this:

```
source 'https://cdn.cocoapods.org'

platform :ios, '17.0'

target 'iosApp' do
    pod 'ComposeApp', :path => '../composeApp'
end
```

No sign of Sentry

**Comment by buenaflor** [comment]
Hmm, are you using xcode16 by any chance?

**Comment by buenaflor** [comment]
And could you try it with cocoa `8.36.0`

```
    pod("Sentry") {
        version = "8.25"
        linkOnly = true
        extraOpts += listOf("-compiler-option", "-fmodules")
    }
```

**Comment by buenaflor** [comment]
I was able to successfully build it with your config. 

I think something is up with your cocoapods setup. Just as a sanity check, do you use the `xcworkspace` instead of `xcodeproj` when running the target?

**Comment by jollygreenegiant** [comment]
Yeah I'm using xcworkspace.  Running XCode 15.4, and updated to version 8.36.0, same error.  Should I try updating XCode?

**Comment by buenaflor** [comment]
It shouldn't be xcode, I'm on 15.4 as well

How does your podfile.lock look like?

**Comment by jollygreenegiant** [comment]
Still the same as above https://github.com/getsentry/sentry-kotlin-multiplatform/issues/274#issuecomment-2380133540

**Comment by jollygreenegiant** [comment]
Podfile doesn't seem to be changing when I build or run `pod deintegrate`

**Comment by buenaflor** [comment]
I meant the `podfile.lock` file, the file contains the versions of pods used, it should be under `iosApp/Podfile.lock`

**Comment by jollygreenegiant** [comment]
```
PODS:
  - ComposeApp (1.0):
    - Sentry (= 8.36.0)
  - Sentry (8.36.0):
    - Sentry/Core (= 8.36.0)
  - Sentry/Core (8.36.0)

DEPENDENCIES:
  - ComposeApp (from `../composeApp`)

SPEC REPOS:
  trunk:
    - Sentry

EXTERNAL SOURCES:
  ComposeApp:
    :path: "../composeApp"

SPEC CHECKSUMS:
  ComposeApp: 3b79a80e04efce07bfa83b593a9ab8a7390739b0
  Sentry: f8374b5415bc38dfb5645941b3ae31230fbeae57

PODFILE CHECKSUM: 4e9acfd8221f63c466f57c440b937980929cb2ad

COCOAPODS: 1.15.2
```

**Comment by buenaflor** [comment]
That looks fine, are you on Kotlin 2.0.20? 

Maybe trying clearing the caches on derived data and also clearing the simulator cache with `xcrun simctl erase all`

as far as I can tell it should be a local caching issue.

**Comment by jollygreenegiant** [comment]
Yeah Kotlin 2.0.20 - cleared both caches you mentioned, cleaned and built, got the same error.  Builds fine but crashes when running on a simulator

**Comment by buenaflor** [comment]
My last suggestions: 

in the cocoapods framework block set `isStatic = true`

```kotlin
framework {
    baseName = "ComposeApp"
    isStatic = true
}
```

If that also fails, could you upload your project or if it's a private repo a sample project on github so I can try to reproduce it

**Comment by jollygreenegiant** [comment]
Setting `isStatic = true` fixed the issue - thank you so much for your help!
