### ISSUE TITLE
Missing diagnosticLevel in OptionsConfiguration

### ISSUE THREAD

**Issue by XanderZhu** [getsentry/sentry-kotlin-multiplatform#286]
### Problem Statement

At the moment there is no way to configure `diagnosticLevel` form shared code.
Interesting, that this configuration field is documented on the official web site.
https://docs.sentry.io/platforms/kotlin-multiplatform/configuration/options/#diagnostic-level.

**Comment by buenaflor** [comment]
hey, thanks for the issue.

I can include the option in the upcoming release

as for the docs it looks like it uses the java options by default, this is something we should change for sure

**Comment by XanderZhu** [comment]
@buenaflor 
Thank you so fast response!
Looking forward to the new version!
