### ISSUE TITLE
Unable to Integrate Sentry Pod in Kotlin Multiplatform Project

### ISSUE THREAD

**Issue by zhimbura** [getsentry/sentry-kotlin-multiplatform#300]
### Platform

Apple

### Installed

CocoaPods

### Version

0.10.0

### Steps to Reproduce

1. **Create a New Kotlin Multiplatform Project**:
   - Open Android Studio.
   - Select **File > New > New Project**.
   - Choose the **Kotlin Multiplatform Mobile** template.
   - Configure the project to use the **iOS Framework distribution with CocoaPods**.

2. **Configure `build.gradle.kts`**:
   - Apply the `Sentry` Kotlin Multiplatform Gradle plugin by adding the following to the `plugins` block:
     ```kotlin
     plugins {
         id("io.sentry.kotlin.multiplatform.gradle") version "0.10.0"
     }
     ```
   - In the `build.gradle.kts` of the shared module (e.g., `ComposeApp`), add the following to the `cocoapods` block:
     ```kotlin
     cocoapods {
         version = "1.0"
         ios.deploymentTarget = "15"
         pod("Sentry") {
             version = "8.38.0"
             extraOpts += listOf("-compiler-option", "-fmodules")
         }
     }
     ```

3. **Configure `Podfile`**:
   - Open the `iosApp/Podfile` file.
   - Add the following configuration:
     ```ruby
     target 'YOUR_APP_NAME' do
       pod 'ComposeApp', :path => '../ComposeApp'
     end
     ```

4. **Sync Gradle**:
   - In Android Studio, click **Sync Project with Gradle Files** to ensure all dependencies are resolved and configured.

5. **Observe the Error**:
   - During the Gradle sync, the following error occurs:
     ```
     java.lang.IllegalArgumentException: 'SentryMechanismMeta' is going to be declared twice
     ```

This error consistently occurs when integrating the `Sentry` pod and applying the `io.sentry.kotlin.multiplatform.gradle` plugin version `0.10.0` in a Kotlin Multiplatform project using the described configuration.

---

#### Description
While attempting to integrate the `Sentry` CocoaPod in a Kotlin Multiplatform project, the following error occurs during the Gradle build process:

```
> Task :composeApp:cinteropSentryIosSimulatorArm64
Exception in thread "main" java.lang.IllegalArgumentException: 'SentryMechanismMeta' is going to be declared twice
	at org.jetbrains.kotlin.native.interop.gen.KotlinFile.<init>(KotlinCodeModel.kt:261)
	at org.jetbrains.kotlin.native.interop.gen.StubIrBridgeBuilder$kotlinFile$1.<init>(StubIrBridgeBuilder.kt:44)
	at org.jetbrains.kotlin.native.interop.gen.StubIrBridgeBuilder.<init>(StubIrBridgeBuilder.kt:44)
	at org.jetbrains.kotlin.native.interop.gen.StubIrDriver.run(StubIrDriver.kt:154)
	at org.jetbrains.kotlin.native.interop.gen.jvm.MainKt.processCLib(main.kt:379)
	at org.jetbrains.kotlin.native.interop.gen.jvm.MainKt.processCLibSafe(main.kt:244)
	at org.jetbrains.kotlin.native.interop.gen.jvm.MainKt.access$processCLibSafe(main.kt:1)
	at org.jetbrains.kotlin.native.interop.gen.jvm.Interop.interop(main.kt:102)
	at org.jetbrains.kotlin.cli.utilities.InteropCompilerKt.invokeInterop(InteropCompiler.kt:49)
	at org.jetbrains.kotlin.cli.utilities.MainKt.mainImpl(main.kt:23)
	at org.jetbrains.kotlin.cli.utilities.MainKt.main(main.kt:44)
```

#### Environment
- **Kotlin Multiplatform Module Name**: `ComposeApp`
- **iOS Deployment Target**: iOS 15
- **Plugin Version**: 0.10.0
- **CocoaPods Configuration**: 
  ```ruby
  target 'MY APP' do
    pod 'ComposeApp', :path => '../ComposeApp'
  end
  ```
- **Pod Being Integrated**: `Sentry` (version: `8.38.0`)

#### Gradle Configuration Highlights
- **Kotlin Configuration**:
  ```kotlin
  kotlin {
      iosX64()
      iosArm64()
      iosSimulatorArm64()
      cocoapods {
          version = "1.0"
          ios.deploymentTarget = "15"
          pod("Sentry") {
              version = "8.38.0"
              extraOpts += listOf("-compiler-option", "-fmodules")
          }
      }
  }
  ```

I would appreciate any help or workaround to resolve this issue, as I originally had a project with a Regular Framework setup, and I need to make either the Regular Framework or the CocoaPods Framework work on iOS.

### Expected Result

The build should complete successfully, allowing the Sentry CocoaPod to be used in the Kotlin Multiplatform project.

### Actual Result

The build fails with a java.lang.IllegalArgumentException indicating that SentryMechanismMeta is being declared twice.

**Comment by buenaflor** [comment]
You shouldn't need to add the Sentry pod in the cocoapods block, the plugin will do it automatically

I'll have a look

**Comment by buenaflor** [comment]
Could you prepare a demo repo? I couldn't repro it with your config.

**Comment by zhimbura** [comment]
@buenaflor Ok, I see, I removed pod from gradle file, and now I get next error, do you know what does it mean? 

![Image](https://github.com/user-attachments/assets/b90c5b1d-8151-4079-99d8-fdf469941357)
![Image](https://github.com/user-attachments/assets/aa6cdb16-2095-40a2-9d83-e0f63f217301)

I will try a create example later...

**Comment by zhimbura** [comment]
> Could you prepare a demo repo? I couldn't repro it with your config.

@buenaflor 

In default project I got an different error, but it will be helpful maybe 

https://github.com/zhimbura/sentry-compose-multiplatform-example

**Comment by buenaflor** [comment]
well you need to run pod install manually first I assume, you don't have a xcodeworkspace in your iosApp folder. 

this is not sentry specific

**Comment by zhimbura** [comment]
> well you need to run pod init and pod install manually first I assume, you don't have a podfile and xcodeworkspace in your iosApp folder.
> 
> this is not sentry specific

@buenaflor 

I installed pod and still getting an error 

![Image](https://github.com/user-attachments/assets/30296aad-7ab8-415c-bee2-fdc904a61198)

![Image](https://github.com/user-attachments/assets/c8cd75db-671f-45de-9bcb-37445997289f)

**Comment by buenaflor** [comment]
you need to use the .xcworkspace, not .xcodeproj

https://guides.cocoapods.org/using/using-cocoapods.html

**Comment by kahest** [comment]
closing this - pls reply if you still have problems

**Comment by zhimbura** [comment]
Yes, problem was with kotlin integration type and build schemes, so now it works, thanks.
