### ISSUE TITLE
Interop generation for iOS arm64

### ISSUE THREAD

**Issue by ncltg** [getsentry/sentry-kotlin-multiplatform#35]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
Sentry 7.21.0

M1 mac with interop enabled for arm64 and simulatorArm64
### Steps to Reproduce

Add ` pod"Sentry", "~> 7.21.0")` to cocoapods gradle plugin

### Expected Result

Sync succeeds

### Actual Result

Sync step fails in android studio.

it fails on 3 steps :

1. cinteropSentryIosArm64
3. cinteropSentryIosSimulatorArm64
4. shared:cinteropSentryIosX64

Example error log for one of the steps :
[Link](https://gist.github.com/ncltg/0b8c33d25d8f5ac53f3249a00fb14bcb)

### Additional info

When trying to sync the kmp-app sample i get a failure on the following step:
`Task 'wrapper' not found in project ':sentry-samples:kmp-app'.`

So i'm wondering if there might be something wrong in my environment ?

### Question

Are there any requirements to make the interop work on an M1 setting or is it supposed to work out of the box ?

Let me know if you need any more details. Thanks for your help !

**Comment by buenaflor** [comment]
Hey @ncltg, are you opening the sample app in it's own Android Studio project? 

You should open the root project and sync it - the sample app will also sync then because it is embedded as a subproject. You can then run the sample apps from there. I'm also on an M1 so it should work out of the box

**Comment by ncltg** [comment]
Hey @buenaflor,
Indeed I was opening the project from the kmp-app subfolder. When opening from the parent project it work flawlessly.
I had no trouble with interop as in my current project so it must be related to my configuration.

Any idea on what kind of wrong configuration to look for here ?

Thanks again for the prompt reply 😊

**Comment by buenaflor** [comment]
Which plugin versions are you running in your project? Maybe you can post your gradle setup so I can try to reproduce your problem

**Comment by ncltg** [comment]
@buenaflor Your last comment helped me pinpoint the issue actually !

I fixed my problem by updating our `sentry-android` dependency from 5.7.3 to 6.1.4.

After doing so the task failure changed,  which i fixed by using this snippet present in the sample build.gradle :

```
    // workaround for https://youtrack.jetbrains.com/issue/KT-41709 due to having "Meta" in the class name
    // if we need to use this class, we'd need to find a better way to work it out
    targets.withType<org.jetbrains.kotlin.gradle.plugin.mpp.KotlinNativeTarget>().all {
        compilations["main"].cinterops["Sentry"].extraOpts(
            "-compiler-option",
            "-DSentryMechanismMeta=SentryMechanismMetaUnavailable"
        )
    }
```

It seems to work just fine now.

Thanks a lot !

**Comment by buenaflor** [comment]
@ncltg Nice! We're working on having a release this week so stay tuned. Also feel free to open an issue if there's something you'd like to discuss, since it's an experimental SDK we'd love to hear some feedback :) cheers
