### ISSUE TITLE
Not published to maven central

### ISSUE THREAD

**Issue by kpgalligan** [getsentry/sentry-kotlin-multiplatform#40]
This is more of a tracking issue. I'd like to remove our interop from [Kermit](https://github.com/touchlab/Kermit/tree/main/kermit-sentry) and just use this library, but the target isn't yet deployed to maven central. I assume it will be soon, as it says maven central in the readme. It looks like the readme changed recently.

Any update on when the first version will be deployed would be great, thanks!

**Comment by erksch** [comment]
Hey there! This library is super awesome! Is there an ETA for when it will hit maven central?
