### ISSUE TITLE
Question: Why cocoapods and cinterop?

### ISSUE THREAD

**Issue by kpgalligan** [getsentry/sentry-kotlin-multiplatform#41]
There's no "discussions" so I thought I'd ask. I started looking through the code. Is there a reason the library has both direct cinterop and a pod dependency? I would assume the pod is to link for tests, but that seems like it could be wired in directly with linker args. I haven't gone into the actual code much, though. Just curious.

**Comment by buenaflor** [comment]
Some of the APIs from the `sentry-cocoa` sdk are not publicly available such as accessing the function `storeEnvelope` so it was at the time when I added it the easiest way to access it. Is that possible without introducing custom headers and cinterop?

**Comment by kpgalligan** [comment]
I was thinking the other way. No cocoapods. Using that in a library can be tricky. For something like sentry, if the iOS library is relatively stable, I'd just grab and trim the headers to only define what the Kotlin client needs, and run cinterop on that. Running your tests at a library level will require some extra work, but I haven't gone through your code (much) to see how you're doing that. I guess cocoapods in a library isn't that big of a deal, but it would be better if there was like a test-only cocoapods integration.

Anyway, I talk some about cinterop here, although it's already kind of old.

https://www.droidcon.com/2022/06/28/sdk-design-and-publishing-for-kotlin-multiplatform-mobile/

**Comment by buenaflor** [comment]
Oh yes, replacing cocoapods with custom headers is something that we consider as well and will most likely be changed in the future. I opted for using cocoapods since it was the fastest way to get the project going.

**Comment by kpgalligan** [comment]
Yeah, that makes sense 👍
