### ISSUE TITLE
Allow to disable/configure HTTP Client Errors Tracking

### ISSUE THREAD

**Issue by Legion2** [getsentry/sentry-kotlin-multiplatform#75]
The new ios sdk version enabled [HTTP Client Errors](https://docs.sentry.io/platforms/apple/guides/ios/configuration/http-client-errors/) by default, we want to disable it, because we already handle all http errors our self and don't want duplicate data in sentry.

It should be possible to disable/configure the HTTP Client Errors Tracking.

**Comment by buenaflor** [comment]
We've shipped this in `0.1.0`: https://github.com/getsentry/sentry-kotlin-multiplatform/releases/tag/0.1.0
