### ISSUE TITLE
Filename guidelines to expect/actual and platform specific implementations

### ISSUE THREAD

**Issue by buenaflor** [getsentry/sentry-kotlin-multiplatform#88]
As our codebase grows it's important to keep it organized in a way that makes searching for specific implementations easy. 

Example: we specify an `expect class SentryEvent` in our `commonMain` which is called `SentryEvent.kt`.
Now on `commonAppleMain` and `commonJvmMain` the `actual` implementations are also called `SentryEvent.kt` so we have 3 files with the same name.

How Google for example handles it: suffix the filename with the platform -> `SentryEvent.jvm.kt` or `SentryEvent.apple.kt`.

[See here](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:collection/collection/src/jvmMain/kotlin/androidx/collection/ArraySet.jvm.kt) for an example.

This is not publicly endorsed by Google but could be a good starting point on how to organize this.

This could also not be only restricted to expect actuals but in general for any File name that will exist on multiple platforms with the same name. So this could also be helpful for our extensions: `SentryOptionsExtensions.jvm.kt` or `BreadcrumbExtensions.jvm.kt`

Thoughts?

**Comment by buenaflor** [comment]
@marandaneto

**Comment by marandaneto** [comment]
@buenaflor makes sense, if we are adding more and more actual classes, sounds like a good improvement.

**Comment by buenaflor** [comment]
Already implemented and is now the standard going forward
