### ISSUE TITLE
Remove docs from github and refer to sentry-docs as source of truth

### ISSUE THREAD

**Issue by buenaflor** [getsentry/sentry-kotlin-multiplatform#90]
Docs are currently split (here on GitHub and Sentry Docs) and it can be confusing for users to choose which one they should follow.

**Comment by marandaneto** [comment]
What do you mean by split up? can you link/explain what is confusing?

**Comment by buenaflor** [comment]
We have extensive docs for installation and configuration directly here on github (which is the same as the one on sentry-docs). It's easier for the user and more managable to remove it here and just refer to sentry-docs.
