### ISSUE TITLE
Enable minification, obfuscation with Proguard on Android release builds

### ISSUE THREAD

**Issue by buenaflor** [getsentry/sentry-kotlin-multiplatform#91]
Currently we have any minification or obfuscation disabled on Android releases.

https://github.com/getsentry/sentry-kotlin-multiplatform/blob/b79cc791d0e0e977d3d8ffec67ab6a8904614e7e/sentry-kotlin-multiplatform/build.gradle.kts#L22

**Comment by marandaneto** [comment]
@buenaflor I don't think this is necessary, minification happens on the final App, and the optimizations are based on how much of the SDK is used, otherwise, everything else s stripped out, so it's fine to be disabled, to be honest, I think this flag has no effect at all IIRC.

**Comment by buenaflor** [comment]
I see then it's not needed, so we can close this?
