### ISSUE TITLE
Compilation failed: linking globals named when integrate sentry multiplatform

### ISSUE THREAD

**Issue by adtarassov** [getsentry/sentry-kotlin-multiplatform#95]
Hi. I'm trying to integrate sentry multi platform for my project.

<img width="654" alt="Screenshot 2023-05-20 at 15 36 55" src="https://github.com/getsentry/sentry-kotlin-multiplatform/assets/22029248/9212402e-814a-4a46-9261-246b1c746de8">

After integration, I get an error when building for ios

<img width="798" alt="Screenshot 2023-05-20 at 15 37 42" src="https://github.com/getsentry/sentry-kotlin-multiplatform/assets/22029248/93a7a0c2-d87b-4559-807b-e7f907994107">

How can I solve this problem? 
Thank you in advance

**Comment by marandaneto** [comment]
@TheMrDOC111 do any of your modules or dependencies already have Sentry in it?
Also check https://docs.sentry.io/platforms/kotlin-multiplatform/#install
Your `cocoapods` block is slightly different than ours, not sure if that's the case.

**Comment by TheMrDOC111** [comment]
@marandaneto, Hi
No, this is the only place where I integrate sentry

Here is the full connection code:

```
plugins {
  alias(libs.plugins.multiplatform)
  alias(libs.plugins.compose)
  alias(libs.plugins.cocoapods)
  alias(libs.plugins.android.application)
  alias(libs.plugins.libres)
  alias(libs.plugins.buildConfig)
  alias(libs.plugins.kotlinx.serialization)
  alias(libs.plugins.sqlDelight)
  alias(libs.plugins.apollo)
}

kotlin {
  android {
    compilations.all {
      kotlinOptions {
        jvmTarget = "1.8"
      }
    }
  }

  iosX64()
  iosArm64()
  iosSimulatorArm64()

  cocoapods {
    version = "1.0.0"
    summary = "Compose application framework"
    homepage = "empty"
    ios.deploymentTarget = "11.0"
    podfile = project.file("../iosApp/Podfile")
    pod("Sentry", "~> 8.7.2")
    framework {
      baseName = "ComposeApp"
      export("io.sentry:sentry-kotlin-multiplatform:0.1.1")
    }
  }

  sourceSets {
    val commonMain by getting {
      dependencies {
        api("io.sentry:sentry-kotlin-multiplatform:0.1.1")
        implementation(compose.runtime)
        implementation(compose.foundation)
        implementation(compose.material)
        implementation(libs.libres)
        implementation(libs.voyager.navigator)
        implementation(libs.composeImageLoader)
        implementation(libs.napier)
        implementation(libs.kotlinx.coroutines.core)
        implementation(libs.ktor.core)
        implementation(libs.composeIcons.featherIcons)
        implementation(libs.kotlinx.serialization.json)
        implementation(libs.kotlinx.datetime)
        implementation(libs.multiplatformSettings)
        implementation(libs.multiplatformSettings.serialization)
        implementation(libs.multiplatformSettings.noArg)
        implementation(libs.koin.core)
        implementation(libs.koin.core)
        implementation(libs.kstore)
        implementation(libs.apollo.runtime)

        implementation("io.ktor:ktor-client-content-negotiation:2.2.4")
        implementation("io.ktor:ktor-serialization-kotlinx-json:2.2.4")
        implementation("io.ktor:ktor-client-logging:2.2.4")
      }
    }

    val commonTest by getting {
      dependencies {
        implementation(kotlin("test"))
      }
    }

    val androidMain by getting {
      dependencies {
        implementation(libs.androidx.appcompat)
        implementation(libs.androidx.activityCompose)
        implementation(libs.compose.uitooling)
        implementation(libs.kotlinx.coroutines.android)
        implementation(libs.ktor.client.okhttp)
        implementation(libs.sqlDelight.driver.android)
        implementation("io.insert-koin:koin-android:3.3.2")
      }
    }

    val iosX64Main by getting
    val iosArm64Main by getting
    val iosSimulatorArm64Main by getting
    val iosMain by creating {
      dependsOn(commonMain)
      iosX64Main.dependsOn(this)
      iosArm64Main.dependsOn(this)
      iosSimulatorArm64Main.dependsOn(this)
      dependencies {
        implementation(libs.ktor.client.darwin)
        implementation(libs.sqlDelight.driver.native)
      }
    }

    val iosX64Test by getting
    val iosArm64Test by getting
    val iosSimulatorArm64Test by getting
    val iosTest by creating {
      dependsOn(commonTest)
      iosX64Test.dependsOn(this)
      iosArm64Test.dependsOn(this)
      iosSimulatorArm64Test.dependsOn(this)
    }
  }
}
```

```
[versions]

kotlin = "1.8.20"
agp = "7.4.2"
compose = "1.4.0"
androidx-appcompat = "1.6.1"
androidx-activityCompose = "1.7.0"
compose-uitooling = "1.4.1"
libres = "1.1.8"
voyager = "1.0.0-rc05"
composeImageLoader = "1.4.0"
napier = "2.6.1"
buildConfig = "3.1.0"
kotlinx-coroutines = "1.6.4"
ktor = "2.2.4"
composeIcons = "1.1.0"
kotlinx-serialization = "1.5.0"
kotlinx-datetime = "0.4.0"
multiplatformSettings = "1.0.0"
koin = "3.4.0"
kstore = "0.5.0"
sqlDelight = "2.0.0-alpha05"
apollo = "3.8.0"
```

**Comment by buenaflor** [comment]
Hi, could you try using the pod version `8.4.0` of Sentry?

**Comment by marandaneto** [comment]
@buenaflor the docs state `8.7.2`, but we use `8.4.0` https://github.com/getsentry/sentry-kotlin-multiplatform/blob/332164a58e37aba8fca0c17b94efcee3d83a9adc/buildSrc/src/main/java/Config.kt#L37
Should we fix the docs right away? what was the reason for having the newest version?

**Comment by buenaflor** [comment]
@marandaneto I have a PR ready in the sentry docs fixing a couple issues including setting the Cocoa version. 

But I'm not sure if this fixes the error, I tested it out and couldn't reproduce the error with `8.7.2`. I haven't seen that error yet in general myself

**Comment by TheMrDOC111** [comment]
@buenaflor, 
When I changed the version to 8.4.0, it fixed the previous error, but another one appeared 

```
/Users/adtarassov/AndroidStudioProjects/Entity/iosApp/iosApp/iosApp.swift:26:8: error: type 'ComposeView' does not conform to protocol 'UIViewControllerRepresentable'
struct ComposeView: UIViewControllerRepresentable {
       ^
/Users/adtarassov/AndroidStudioProjects/Entity/iosApp/iosApp/iosApp.swift:26:8: note: do you want to add protocol stubs?
struct ComposeView: UIViewControllerRepresentable {
```
But I didn't change anything in this file, most likely the problem is in the generated links

<img width="652" alt="Screenshot 2023-05-22 at 11 15 10" src="https://github.com/getsentry/sentry-kotlin-multiplatform/assets/22029248/bdbe8a5f-aad3-4f54-8dc9-e342703623a6">

**Comment by marandaneto** [comment]
@TheMrDOC111 that does not seem related to Sentry though.

**Comment by TheMrDOC111** [comment]
@marandaneto, maybe. But this error appears only when I connect Sentry 8.4.0. If I don't integrate Sentry, ios project builds fine

**Comment by buenaflor** [comment]
@TheMrDOC111 If you could provide a minimal reproducible sample it would be greatly helpful, this might be an edge case since we don't have explicit support for iOS compose yet

**Comment by adtarassov** [comment]
> @TheMrDOC111 If you could provide a minimal reproducible project sample it would be greatly helpful, this might be an edge case since we don't have explicit support for iOS compose yet and since it's compose ios still alpha it's hard to tell what's wrong from code snippets.
> 
> Other than that I'd suggest for you to remove `export("io.sentry:sentry-kotlin-multiplatform:0.1.1")` from your framework configuration in `build.gradle.kts` and see what happens.
> 
> I suspect the issue is that `io.sentry.kotlin.multiplatform.Context` clashes with the `Context` from Compose that's why it might not be able to conform to the `UIViewControllerRepresentable` protocol when exporting it as a framework.
> 
> We are currently working on improving the docs as exporting the framework is not necessary to install the SDK but rather optional.

Oh my God.
I deleted export("io.sentry:sentry-kotlin-multiplatform:0.2.0") and now everything is working. Thank you very much!
